### ISSUE TITLE
Package taskbar-never-combine must restat explorer.exe

### ISSUE THREAD

**Issue by artur99** [neutmute/nm-chocolatey-packs#5]
The powershell script for `taskbar-never-combine` would need to restart `explore.exe` after changing the regedit field, as it won't update immediately (Tested on a `Windows 10 Enterprise x64`).

Thank you!

**Comment by neutmute** [comment]
Hey - I understand but having chocolatey end the explorer process is undesirable too IMHO. I'll leave this is as `won't-fix`
