### ISSUE TITLE
[Bug] AgentRansack not installed quietly

### ISSUE THREAD

**Issue by Kristinita** [neutmute/nm-chocolatey-packs#6]
### 1. Summary

AgentRansack package not installed quietly for me.

### 2. Steps to reproduce

I install Chocolatey → `choco install agentrasnack -y` → in installation process I get window:

![AgentRansack](http://i.imgur.com/SXyqFmU.png)

And I need install AgentRansack not silently.

I'm sorry, I have similar problem with [**The Wonderful Icon**](http://stackoverflow.com/q/41381204/5951529) program. I do not know much AutoHotkey, and I can not to make pull request independently.

### 3. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Chocolatey:**
0.10.3

Thanks.

**Comment by neutmute** [comment]
I wonder if the difference is x86? I just installed AgentRansack on a new x64 and it went fine

**Comment by Kristinita** [comment]
@neutmute , I also install AgentRansack in my Windows x64 successfully. I think, the problem in this line: [**WinWait, Agent Ransack x64 Setup, , 60**](https://github.com/neutmute/nm-chocolatey-packs/blob/master/agentransack/tools/agent-ransack-install.ahk#L6).

Thanks.

**Comment by neutmute** [comment]
thanks for the pointer - hopefully fixed in 8.0.865.1- i extended some of the wait timers before keypresses.
